name: PortalZones
version: '1.0.0'
main: com.playdeca.portalzones.PortalZones
api-version: '1.20'

commands:
    portalzone:
        description: Portal Zones command
        usage: /pz <command> [args]
        permission: portalzones.command
        aliases: [portalzones, pz]
        permission-message: You do not have permission to use this command.
    pz:
        description: Portal Zones command
        usage: /pz <command> [args]
        permission: portalzones.command
        aliases: [portalzones, pz]
        permission-message: You do not have permission to use this command.
