name: PortalZones
version: '${version}'
main: com.playdeca.portalzones.PortalZones
api-version: '1.20'

commands:
    pz:
        description: Portal Zones command
        usage: /pz <create|list|delete|modify>
        permission: portalzones.command
    portalzones:
        description: Portal Zones command
        usage: /portalzones <create|list|delete|modify>
        permission: portalzones.command